name: Upload PR artifact
on:
  push:
    branches:
      - develop
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: write payload
        run: cat $GITHUB_EVENT_PATH > payload.json
      - uses: actions/upload-artifact@v2
        with:
          name: payload
          path: payload.json
