name: Upload PR artifact
on:
  push:
    branches:
      - develop
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: event-json
          path: ${GITHUB_EVENT_PATH}
