name: Create Pull Request
on:
  push:
    branches:
      - feature/**
      - feat/**
      - refactor/**
      - chore/**
      - docs/**
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
    #   - name: Create Pull Request
    #     uses: peter-evans/create-pull-request@v3
    #     with:
    #       name:
