name: dep-command
on:
  workflow_dispatch:
    inputs:
      repository-name:
        description: "The name of the repository from which the slash command was dispatched"
        required: true
      repository-owner:
        description: "The owner of the repository from which the slash command was dispatched"
        required: true
      issue-number:
        description: "The issue number in which the slash command was made"
        required: true
      html-url:
        description: "URL where comment was created"
        required: true
      cluster:
        description: "The cluster to deploy to"
        required: true
      commit:
        description: "Commit ID to deploy"
        required: false
      branch:
        description: "Branch to deploy"
        required: false
jobs:
  deploy:
    runs-on: macos-latest
    name: A job to test new action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Store inputs as JSON
        env:
          WORKFLOW_INPUTS: ${{ toJson(github.event.inputs) }}
        run: echo "$WORKFLOW_INPUTS"
      - name: set up actions binary
        run: |
          mkdir -p github-actions/bin
          mv actions github-actions/bin
          chmod +x github-actions/bin/actions
          echo "::add-path::$GITHUB_WORKSPACE/github-actions/bin"
      - name: extract and set vars
        id: vars
        run: |
          actions --log-level debug pcd -j $WORKFLOW_INPUTS
      # - name: print vars
      #   run: |
      #     echo ref: ${{ steps.vars.outputs.ref }}
      #     echo cluster: ${{ steps.vars.outputs.cluster }}
      #     echo image_tag: ${{ steps.vars.outputs.image_tag }}
