name: dep-command
on:
  workflow_dispatch:
    inputs:
      #   repository:
      #     description: "The repository from which the slash command was dispatched"
      #     required: true
      #   issue-number:
      #     description: "The issue number in which the slash command was made"
      #     required: true
      #   cluster:
      #     description: "The cluster to deploy to"
      #     required: true
      commit:
        description: "Commit ID to deploy"
        required: false
      type:
        description: "Type to deploy (used to specify PR)"
        required: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: A job to test new action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Store inputs as JSON
        env:
          WORKFLOW_INPUTS: ${{ toJson(github.events.inputs) }}
        run: echo "$WORKFLOW_INPUTS"
