name: Deploy Slash Command
on:
  repository_dispatch:
    types: [deploy-command]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch and cluster
        id: vars
        run: |
          branch=${{ github.event.client_payload.slash_command.args.named.branch }}
          if [[ -z "$branch" ]]; then branch="develop"; fi
          echo ::set-output name=branch::$branch
          cluster=${{ github.event.client_payload.slash_command.args.named.cluster }}
          if [[ -z "$cluster" ]]; then exit 1; fi
          echo ::set-output name=cluster::$cluster
      - name: Print vars
        run: |
          echo "${{ steps.vars.outputs.branch }}"
          echo "${{ steps.vars.outputs.cluster }}"
          echo ${{ steps.vars.outputs.branch }}
          echo ${{ steps.vars.outputs.cluster }}
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"
