name: Deploy Bananas
on:
  repository_dispatch:
    types: [banana-command]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test new action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Dump the context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.context) }}
        run: echo "$PAYLOAD_CONTEXT"
      - name: Install
        run: yarn install
      - name: Extract necessary vars
        id: vars
        uses: ./
      - name: Print vars
        run: |
          echo ref: ${{ steps.vars.outputs.ref }}
          echo cluster: ${{ steps.vars.outputs.cluster }}
          echo image_tag: ${{ steps.vars.outputs.image_tag }}
          echo short_sha: ${{ steps.vars.outputs.short_sha }}
