name: Hello World
on:
  repository_dispatch:
    types: [deploy-command]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install
        run: yarn install
      - name: Hello world action step
        id: hello
        uses: ./
        with:
          who-to-greet: "Mona the Octocat"
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
