name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
        - name: Output comment
          run: echo ${{github.event.issue.body}}
        - name: Parse slash command 
          run: echo ${{github.event.issue.body}} | head -n 1 | grep -E '^/deploy'
        - name: Check if correct
          if: ${{success()}}
          run: echo 'got deploy slash command' 
        - name: Check if incorrect
          if: ${{failure()}}
          run: echo 'not a deploy slash command' 
 
