name: Upload Artifact
on: push
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Write payload
        run: cat $GITHUB_EVENT_PATH > payload.json
      - name: Upload payload
        uses: actions/upload-artifact@v2
        with:
          name: payload
          path: payload.json
